apiVersion: v1
kind: Service
metadata:
  name: doks-flask
  namespace: dev
  labels:
    app: doks-flask
spec:
  type: ClusterIP
  selector:
    app: doks-flask
  ports:
  - name: http
    port: 80
    targetPort: 8080